version: '3.3'

services:
  db:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test1234
    ports:
      - 3306:3306
    networks:
      - test

networks:
  test:
    driver: "bridge"

volumes:
  db_data: {}
